"use client";
import { ArrowLeft, Check, ChevronDown, Film, FolderOpen, ImagePlus, LoaderCircle, Sparkles, Upload, Video, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { FormEvent, useEffect, useRef, useState } from "react";
type Item={preview:string;name:string;byteSize:number;file?:File;assetId?:string}; type Asset={id:string;mimeType:string;byteSize:number;originalName:string;url:string}; type Account={wallet:{availablePoints:number}};
const imageAccept="image/jpeg,image/png,image/webp";
export function RecreateVideoPage(){const router=useRouter();const refs={video:useRef<HTMLInputElement>(null),product:useRef<HTMLInputElement>(null),scene:useRef<HTMLInputElement>(null)};const[account,setAccount]=useState<Account|null>(null);const[reference,setReference]=useState<Item|null>(null);const[products,setProducts]=useState<Item[]>([]);const[scene,setScene]=useState<Item|null>(null);const[tab,setTab]=useState<"video"|"product"|"scene"|null>(null);const[assets,setAssets]=useState<Asset[]>([]);const[info,setInfo]=useState("");const[special,setSpecial]=useState("");const[modelOn,setModelOn]=useState(false);const[modelInfo,setModelInfo]=useState("");const[ratio,setRatio]=useState("9:16");const[duration,setDuration]=useState("15");const[resolution,setResolution]=useState("720p");const[phase,setPhase]=useState("idle");const[error,setError]=useState("");
useEffect(()=>{fetch("/api/auth/session/",{cache:"no-store"}).then(async r=>{if(!r.ok)throw Error();setAccount(await r.json())}).catch(()=>router.replace("/"))},[router]);
const choose=(kind:"video"|"product"|"scene",files?:FileList|null)=>{if(!files?.length)return;const list=Array.from(files);if(kind==="video"){const f=list[0];if(f.type!=="video/mp4")return setError("对标视频仅支持 MP4");if(f.size>100*1024*1024)return setError("对标视频不能超过 100MB");setReference({file:f,preview:URL.createObjectURL(f),name:f.name,byteSize:f.size})}else{const valid=list.filter(f=>["image/jpeg","image/png","image/webp"].includes(f.type)&&f.size<=10*1024*1024).map(f=>({file:f,preview:URL.createObjectURL(f),name:f.name,byteSize:f.size}));if(kind==="scene")setScene(valid[0]||null);else setProducts(c=>[...c,...valid].slice(0,5));}setError("");setPhase("idle")};
const openLibrary=async (kind:"video"|"product"|"scene")=>{setTab(kind);const r=await fetch("/api/assets/?kind=ALL",{cache:"no-store"});const b=await r.json();if(!r.ok)return setError("素材库加载失败");setAssets((b.assets||[]).filter((a:Asset)=>kind==="video"?a.mimeType==="video/mp4":a.mimeType.startsWith("image/")))};
const select=(a:Asset)=>{const x={assetId:a.id,preview:a.url,name:a.originalName,byteSize:a.byteSize};if(tab==="video")setReference(x);if(tab==="scene")setScene(x);if(tab==="product")setProducts(c=>c.some(i=>i.assetId===a.id)?c.filter(i=>i.assetId!==a.id):c.length<5?[...c,x]:c);setTab(null)};
const upload=async(i:Item)=>{if(i.assetId)return i.assetId;if(!i.file)throw Error("素材未找到");const r=await fetch("/api/uploads/presign/",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({fileName:i.file.name,mimeType:i.file.type,byteSize:i.file.size})});const p=await r.json();if(!r.ok)throw Error(p.message||"上传失败");if(!(await fetch(p.uploadUrl,{method:"PUT",headers:{"Content-Type":i.file.type},body:i.file})).ok)throw Error("上传失败");if(!(await fetch("/api/uploads/confirm/",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({assetId:p.assetId})})).ok)throw Error("素材校验失败");return p.assetId};
const submit=async(e:FormEvent)=>{e.preventDefault();if(!reference||!products.length||phase!=="idle")return;setPhase("uploading");try{const ids=[...await Promise.all(products.map(upload)),await upload(reference),...(scene?[await upload(scene)]:[])];const prompt=[`产品信息：${info}`,`视频特殊要求：${special}`,modelOn?`自定义模特信息：${modelInfo}`:""].filter(Boolean).join("\n");const r=await fetch("/api/tasks/recreate-video/",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({assetIds:ids,prompt,aspectRatio:ratio,duration:Number(duration),resolution,scene:"镜头节奏复刻",style:"自然带货"})});const b=await r.json();if(!r.ok)throw Error(b.message||b.code);setPhase("generating")}catch(err){setError(err instanceof Error?err.message:"创建失败");setPhase("idle")}};
const box=(kind:"video"|"product"|"scene",title:string,required:boolean,desc:string,Icon:typeof Video)=>{const item=kind==="video"?reference:kind==="scene"?scene:null;return <section className="recreate-source"><div className="ad-field-title">{title} {required&&<em>*</em>}</div><div className="ad-source-tabs"><button type="button" className={tab!==kind?"active":""} onClick={()=>refs[kind].current?.click()}><Upload size={16}/>本地上传</button><button type="button" className={tab===kind?"active":""} onClick={()=>openLibrary(kind)}><FolderOpen size={17}/>资产库</button></div>{tab===kind?<div className="recreate-library">{assets.map(a=><button type="button" key={a.id} onClick={()=>select(a)}><img src={a.url} alt=""/><small>{a.originalName}</small></button>)}</div>:<button type="button" className="ad-dropzone recreate-drop" onClick={()=>refs[kind].current?.click()}><span><Icon size={27}/></span><strong>{title}</strong><small>{desc}</small><small>{kind==="product"?`已上传 ${products.length}/5 个`:item?"已选择 1 个":"已上传 0/1 个"}</small><input ref={refs[kind]} type="file" accept={kind==="video"?"video/mp4":imageAccept} multiple={kind==="product"} onChange={e=>choose(kind,e.target.files)}/></button>}</section>};
if(!account)return <main className="workspace-loading"><Sparkles/></main>;return <main className="recreate-studio"><header className="ad-studio-header"><button onClick={()=>router.push("/create/product-video")}><ArrowLeft size={19}/>返回视频创作</button></header><form className="recreate-card" onSubmit={submit}><div className="ad-studio-title"><Film size={22}/><strong>复刻爆款带货视频-新版</strong></div><div className="ad-studio-body">{box("video","对标视频",true,"视频时长需在 3–20 秒之间",Video)}{box("product","商品图",true,"上传商品图片，支持多张",ImagePlus)}<label className="recreate-toggle">自定义模特信息 <input type="checkbox" checked={modelOn} onChange={e=>setModelOn(e.target.checked)}/><i/></label>{modelOn&&<label className="ad-form-field">模特信息（可选）<textarea value={modelInfo} onChange={e=>setModelInfo(e.target.value)} placeholder="例如：女性，25 岁，自然亲和，居家穿搭"/></label>}{box("scene","场景图（选填）",false,"上传希望出现的商品场景",ImagePlus)}<label className="ad-form-field">产品信息（可选）<textarea value={info} onChange={e=>setInfo(e.target.value)} placeholder="例如：产品名称、核心卖点、材质、目标人群"/></label><label className="ad-form-field">视频特殊要求（可选）<textarea value={special} onChange={e=>setSpecial(e.target.value)} placeholder="例如：突出金属质感、镜头缓慢推进、电影级光影"/></label><div className="ad-select-grid"><label>视频比例 <em>*</em><span className="ad-select"><select value={ratio} onChange={e=>setRatio(e.target.value)}><option value="9:16">竖屏（9:16）</option><option value="16:9">横屏（16:9）</option></select><ChevronDown size={16}/></span></label><label>视频时长 <em>*</em><span className="ad-select"><select value={duration} onChange={e=>setDuration(e.target.value)}><option value="5">5 秒</option><option value="10">10 秒</option><option value="15">15 秒</option></select><ChevronDown size={16}/></span></label><label>视频分辨率 <em>*</em><span className="ad-select"><select value={resolution} onChange={e=>setResolution(e.target.value)}><option>480p</option><option>720p</option><option>1080p</option></select><ChevronDown size={16}/></span></label></div>{error&&<p className="creator-error">{error}</p>}<div className="ad-actions"><button className="ad-generate" disabled={!reference||!products.length||phase!=="idle"}>{phase==="uploading"?<LoaderCircle size={18}/>:<Film size={18}/>}生成复刻带货视频</button></div></div></form></main>}
