"use client";

import { BookOpen, Coins, ExternalLink, LoaderCircle, ReceiptText, WalletCards } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { AppShell, LoadingScreen } from "@/app/components/app-shell";

type Account = { user: { displayName: string }; wallet: { availablePoints: number } };
type LedgerItem = { id: string; label: string; description: string; changeText: string; tone: "income" | "expense" | "hold" | "neutral"; availableBalanceAfter: number; taskId: string | null; createdAt: string };
type Payment = { id: string; orderNo: string; status: string; statusLabel: string; amountCny: number; points: number; description: string; createdAt: string; paidAt: string | null };
type WalletData = { wallet: { availablePoints: number; frozenPoints: number }; rules: Array<{ title: string; content: string }>; ledger: LedgerItem[]; payments: Payment[] };

export default function WalletPage() {
  const router = useRouter(); const [account, setAccount] = useState<Account | null>(null); const [data, setData] = useState<WalletData | null>(null);
  useEffect(() => { fetch("/api/auth/session/", { cache: "no-store" }).then(async (r) => { if (!r.ok) throw new Error(); setAccount(await r.json()); }).catch(() => router.replace("/")); }, [router]);
  useEffect(() => { if (account) fetch("/api/wallet/", { cache: "no-store" }).then(async (r) => { if (!r.ok) throw new Error(); setData(await r.json()); }).catch(() => router.replace("/")); }, [account, router]);
  if (!account) return <LoadingScreen />;
  return <AppShell active="wallet" account={account}><div className="app-page-content"><section className="page-intro"><div><span className="page-kicker"><WalletCards size={15} />账户资产</span><h1>积分钱包</h1><p>充值、冻结、成功扣款和退款均以站内明细为准。</p></div></section>{!data ? <div className="records-loading"><LoaderCircle size={22} />正在载入钱包</div> : <><section className="wallet-summary"><div><Coins size={22} /><span>可用积分</span><strong>{data.wallet.availablePoints.toLocaleString()}</strong></div><div><WalletCards size={22} /><span>冻结中</span><strong>{data.wallet.frozenPoints.toLocaleString()}</strong></div><div><BookOpen size={22} /><span>积分换算</span><strong>1 元 = 10 积分</strong></div></section><section className="wallet-layout"><div className="wallet-main-column"><div className="wallet-panel"><div className="section-title"><div><h2>积分收支明细</h2><p>任务创建先冻结，成功后从冻结积分扣款，失败或取消原路退回。</p></div></div>{data.ledger.length ? <div className="ledger-list">{data.ledger.map((item) => <div key={item.id}><div className="ledger-primary"><strong>{item.label}</strong><small>{item.description}</small><time>{new Date(item.createdAt).toLocaleString("zh-CN")}</time>{item.taskId && <Link href={`/tasks/${item.taskId}`}><ExternalLink size={12} />查看任务</Link>}</div><em className={`ledger-change ${item.tone}`}>{item.changeText}</em><span className="ledger-balance">可用余额 {item.availableBalanceAfter}</span></div>)}</div> : <div className="page-empty compact"><strong>暂无积分流水</strong></div>}</div><div className="wallet-panel payment-history"><div className="section-title"><div><h2>支付明细</h2><p>展示当前账号发起的微信支付订单及到账状态。</p></div></div>{data.payments.length ? <div className="payment-list">{data.payments.map((payment) => <div key={payment.id}><ReceiptText size={17} /><div><strong>{payment.description}</strong><small>订单号 {payment.orderNo} · {new Date(payment.createdAt).toLocaleString("zh-CN")}</small></div><span>¥{payment.amountCny.toFixed(2)} / {payment.points} 积分</span><em className={`payment-status status-${payment.status.toLowerCase()}`}>{payment.statusLabel}</em></div>)}</div> : <div className="page-empty compact"><ReceiptText size={24} /><strong>暂无支付订单</strong><p>微信支付尚未开放；充值码到账会记录在上方积分明细中。</p></div>}</div></div><aside className="wallet-panel rules-panel"><div className="section-title"><div><h2>积分规则</h2></div></div>{data.rules.map((rule) => <div className="wallet-rule" key={rule.title}><strong>{rule.title}</strong><p>{rule.content}</p></div>)}</aside></section></>}</div></AppShell>;
}
