"use client";

import { CheckCircle2, KeyRound, LoaderCircle, Save, UserRound } from "lucide-react";
import { useRouter } from "next/navigation";
import { FormEvent, useEffect, useState } from "react";
import { AppShell, LoadingScreen } from "@/app/components/app-shell";

type Account = { user: { displayName: string; isAdministrator?: boolean }; wallet: { availablePoints: number } };
type Profile = { displayName: string; identifier: string; createdAt: string };

export default function AccountPage() {
  const router = useRouter(); const [account, setAccount] = useState<Account | null>(null); const [profile, setProfile] = useState<Profile | null>(null); const [displayName, setDisplayName] = useState(""); const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { Promise.all([fetch("/api/auth/session/", { cache: "no-store" }), fetch("/api/account/", { cache: "no-store" })]).then(async ([session, detail]) => { if (!session.ok || !detail.ok) throw new Error(); const nextAccount = await session.json(); const nextProfile = await detail.json(); setAccount(nextAccount); setProfile(nextProfile); setDisplayName(nextProfile.displayName); }).catch(() => router.replace("/")); }, [router]);
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setMessage(""); try { const response = await fetch("/api/account/", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ displayName, currentPassword, newPassword }) }); const body = await response.json(); if (!response.ok) throw new Error(body.message || "保存失败"); setMessage(body.passwordChanged ? "资料和密码已更新" : "资料已保存"); setCurrentPassword(""); setNewPassword(""); setAccount((current) => current ? { ...current, user: { ...current.user, displayName: body.displayName } } : current); setProfile((current) => current ? { ...current, displayName: body.displayName } : current); } catch (error) { setMessage(error instanceof Error ? error.message : "保存失败"); } finally { setSaving(false); } };
  if (!account || !profile) return <LoadingScreen />;
  return <AppShell active="account" account={account}><div className="app-page-content"><section className="page-intro"><div><span className="page-kicker"><UserRound size={15} />账户中心</span><h1>账号设置</h1><p>管理个人资料与登录密码。账号标识需要通过客服及验证流程变更。</p></div></section><section className="account-layout"><aside className="account-summary"><span className="account-avatar">{profile.displayName.slice(0, 1)}</span><strong>{profile.displayName}</strong><small>{profile.identifier}</small><p>注册于 {new Date(profile.createdAt).toLocaleDateString("zh-CN")}</p></aside><form className="account-form" onSubmit={submit}><section><div className="account-section-title"><UserRound size={18} /><div><h2>个人资料</h2><p>昵称会显示在工作台和账户菜单中。</p></div></div><label>昵称<input value={displayName} onChange={(event) => setDisplayName(event.target.value)} maxLength={32} required /></label><label>账号标识<input value={profile.identifier} disabled /></label></section><section><div className="account-section-title"><KeyRound size={18} /><div><h2>修改密码</h2><p>不修改请留空；修改后当前设备将继续保持登录。</p></div></div><label>当前密码<input value={currentPassword} onChange={(event) => setCurrentPassword(event.target.value)} type="password" autoComplete="current-password" /></label><label>新密码<input value={newPassword} onChange={(event) => setNewPassword(event.target.value)} type="password" autoComplete="new-password" minLength={8} maxLength={72} placeholder="8–72 位密码" /></label></section>{message && <p className="account-message"><CheckCircle2 size={16} />{message}</p>}<button className="account-save" disabled={saving}>{saving ? <LoaderCircle size={17} /> : <Save size={17} />}{saving ? "保存中" : "保存设置"}</button></form></section></div></AppShell>;
}
