export type ImageWorkflowCase = {
  id: string;
  title: string;
  tag: string;
  image: string;
  prompt: string;
  productDescription?: string;
  ratio?: string;
  scene?: string;
  style?: string;
};

export const aiImageCases: ImageWorkflowCase[] = [
  {
    id: "orange-cat",
    title: "超写实写真智能手机抓拍人像摄影",
    tag: "图片案例",
    image: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=900&q=88",
    prompt: "超写实手机抓拍质感的人像摄影，夜晚城市暖光背景，自然姿态，浅景深，真实皮肤纹理，电影感光影，画面高级且自然。",
    ratio: "9:16",
    scene: "自由创作",
    style: "真实摄影",
  },
  {
    id: "perfume-still",
    title: "POV 夜间约会肖像",
    tag: "图片案例",
    image: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=88",
    prompt: "POV 视角夜间约会肖像，人物看向镜头，餐厅暖光、玻璃反射、自然笑容，手机摄影真实质感，高级浅景深。",
    ratio: "9:16",
    scene: "人物氛围",
    style: "真实摄影",
  },
  {
    id: "neon-sneaker",
    title: "动漫 / 杂志杂志封面插画",
    tag: "图片案例",
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=88",
    prompt: "未来感潮流杂志封面插画，年轻角色穿机能服装，强烈版式构图，东京街头元素，鲜明色彩，封面级视觉但不要生成可读文字。",
    ratio: "3:4",
    scene: "自由创作",
    style: "插画质感",
  },
  {
    id: "stadium-cheer",
    title: "体育宣传海报",
    tag: "图片案例",
    image: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?auto=format&fit=crop&w=900&q=88",
    prompt: "体育赛事宣传海报，热烈球场氛围，人物举起围巾欢呼，绿色与黄色主色，灯光强烈，动感商业摄影，清晰主体。",
    ratio: "4:3",
    scene: "人物氛围",
    style: "明快促销",
  },
  {
    id: "fashion-green",
    title: "时尚肖像照",
    tag: "图片案例",
    image: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=900&q=88",
    prompt: "时尚肖像摄影，荧光绿色造型，湿润透明背景材质，人物佩戴夸张眼镜，棚拍灯光，强烈潮流杂志质感。",
    ratio: "3:4",
    scene: "人物氛围",
    style: "清透商业",
  },
  {
    id: "summer-poster",
    title: "时尚海报",
    tag: "图片案例",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=88",
    prompt: "夏日街头潮流海报，霓虹涂鸦背景，动感人物姿态，紫色和黄色高对比，商业宣传视觉，强烈层次感，不要生成可读文字。",
    ratio: "4:3",
    scene: "自由创作",
    style: "明快促销",
  },
];

export const productSceneCases: ImageWorkflowCase[] = [
  {
    id: "coffee-table",
    title: "咖啡桌面场景",
    tag: "食品饮品",
    image: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=900&q=88",
    productDescription: "精品咖啡或饮品杯，主打现制饮品、香气和社交分享场景。",
    prompt: "把商品自然放在咖啡桌面，双手拿起杯子碰杯，背景有柔焦咖啡机和暖色灯光，真实门店生活方式摄影。",
    ratio: "1:1",
    scene: "咖啡桌面",
    style: "明亮生活方式",
  },
  {
    id: "outdoor-bottle",
    title: "户外通勤水杯",
    tag: "家居百货",
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=900&q=88",
    productDescription: "绿色随行水杯，磨砂质感，适合通勤、运动和户外补水，强调简洁、便携、耐用。",
    prompt: "把商品置于干净浅色背景或户外桌面，突出杯身轮廓和瓶盖结构，柔和自然光，干净商业构图。",
    ratio: "9:16",
    scene: "户外生活",
    style: "低饱和质感",
  },
  {
    id: "gift-watch",
    title: "礼盒精品陈列",
    tag: "珠宝配饰",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=88",
    productDescription: "白色智能腕表或配饰礼盒，适合礼赠、节日促销和精品陈列。",
    prompt: "把商品放在浅灰礼盒场景中，两个商品形成对角构图，轻奢质感，柔和阴影，突出材质细节。",
    ratio: "1:1",
    scene: "节日礼赠",
    style: "轻奢商业",
  },
  {
    id: "baby-romper",
    title: "婴儿飞袖纯棉连体衣",
    tag: "母婴服饰",
    image: "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=900&q=88",
    productDescription: "婴儿纯棉连体衣，柔软亲肤，适合居家穿着和母婴店展示。",
    prompt: "把商品呈现在明亮婴儿房或柔软床品场景，浅色背景，温柔自然光，强调亲肤和柔软质感。",
    ratio: "9:16",
    scene: "自然居家",
    style: "明亮生活方式",
  },
  {
    id: "male-pants",
    title: "产品场景图-裤子",
    tag: "服饰穿搭",
    image: "https://images.unsplash.com/photo-1516257984-b1b4d707412e?auto=format&fit=crop&w=900&q=88",
    productDescription: "男士休闲裤，宽松版型，适合通勤和日常穿搭。",
    prompt: "让模特在室内门廊自然站立，穿着商品裤子，光线柔和，强调裤型、垂坠感和日常穿搭氛围。",
    ratio: "9:16",
    scene: "精品店陈列",
    style: "低饱和质感",
  },
  {
    id: "female-pants",
    title: "产品场景图-裤子",
    tag: "服饰穿搭",
    image: "https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=900&q=88",
    productDescription: "女士休闲阔腿裤，高腰版型，适合居家、通勤和轻运动场景。",
    prompt: "让模特在自然居家卧室场景中穿着商品裤子，站姿自然，浅色床品背景，强调裤型和面料舒适度。",
    ratio: "9:16",
    scene: "自然居家",
    style: "明亮生活方式",
  },
];

export const productHeroCases: ImageWorkflowCase[] = [
  {
    id: "clean-bottle-hero",
    title: "通勤水杯清爽主图",
    tag: "商品主图",
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=900&q=88",
    productDescription: "磨砂随行水杯，主打通勤、运动补水和简洁耐用。",
    prompt: "生成干净电商首图，商品居中偏下，浅色背景，柔和自然阴影，保留上方留白用于后期排版，突出杯身轮廓和材质。",
    ratio: "1:1",
    scene: "简约家居",
    style: "清透商业",
  },
  {
    id: "beauty-bottle-hero",
    title: "香氛精修陈列主图",
    tag: "商品主图",
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=88",
    productDescription: "香氛或护肤瓶装产品，强调玻璃材质、精致反光和礼赠质感。",
    prompt: "棚拍质感商品主图，柔光反射，浅灰或奶白背景，商品边缘清晰，高级低饱和，避免文字、价格和多余品牌元素。",
    ratio: "3:4",
    scene: "纯色棚拍",
    style: "低饱和高级",
  },
  {
    id: "home-storage-hero",
    title: "轻奢家居陈列主图",
    tag: "商品主图",
    image: "https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=900&q=88",
    productDescription: "家居收纳或生活方式商品，适合店铺首屏展示。",
    prompt: "在简约家居场景中生成商品首图，背景干净、光线柔和、商品主体明确，保留电商留白，整体克制高级。",
    ratio: "4:3",
    scene: "简约家居",
    style: "真实摄影",
  },
];

export const productDetailCases: ImageWorkflowCase[] = [
  {
    id: "kitchen-detail",
    title: "厨房小家电详情页",
    tag: "详情页",
    image: "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=900&q=88",
    productDescription: "厨房小家电，主打容量、易清洁、安全材质和日常效率。",
    prompt: "生成商品详情页套图：开场氛围、核心卖点、材质细节、使用场景、收束展示五个模块。不要生成可读文字，保留排版留白。",
    ratio: "9:16",
    scene: "简约品牌",
    style: "清晰卖点",
  },
  {
    id: "skincare-detail",
    title: "护肤品详情页套图",
    tag: "详情页",
    image: "https://images.unsplash.com/photo-1612817288484-6f916006741a?auto=format&fit=crop&w=900&q=88",
    productDescription: "护肤精华或面霜，强调质地、成分感、温和修护和精致包装。",
    prompt: "生成美妆详情页视觉：产品瓶身、质地延展、手部使用、浴室/梳妆台场景、礼赠陈列。画面干净高级，不生成文字。",
    ratio: "9:16",
    scene: "轻奢质感",
    style: "真实摄影",
  },
  {
    id: "travel-bag-detail",
    title: "通勤箱包详情页",
    tag: "详情页",
    image: "https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=900&q=88",
    productDescription: "通勤包，主打容量分区、皮革纹理、五金细节和商务穿搭。",
    prompt: "生成箱包详情页长图模块：整体轮廓、容量展示、材质细节、通勤上身/手提场景、收纳对比。避免可读文字和价格。",
    ratio: "9:16",
    scene: "自然生活",
    style: "克制留白",
  },
];

export const recreateHeroCases: ImageWorkflowCase[] = [
  {
    id: "layout-clean-recreate",
    title: "干净留白主图复刻",
    tag: "复刻主图",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=88",
    productDescription: "参考清爽电商构图，只复刻布局节奏，不复制原图内容。",
    prompt: "提取参考图的主体位置、留白比例、光线方向和背景层次，用上传商品生成原创主图。不要复制参考图中的具体商品、文字或品牌。",
    ratio: "1:1",
    scene: "构图复刻",
    style: "原创商业",
  },
  {
    id: "premium-recreate",
    title: "高级棚拍主图复刻",
    tag: "复刻主图",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=900&q=88",
    productDescription: "参考高级棚拍质感，重建商品光影和材质表达。",
    prompt: "复刻参考图的棚拍光影、反射质感和层次关系，商品主体必须换成上传商品，整体原创且无文字水印。",
    ratio: "3:4",
    scene: "氛围复刻",
    style: "真实摄影",
  },
];

export const recreateDetailCases: ImageWorkflowCase[] = [
  {
    id: "benefit-flow-detail",
    title: "卖点结构复刻",
    tag: "复刻商详",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=88",
    productDescription: "参考竞品详情页的卖点顺序，生成原创商品详情页视觉。",
    prompt: "提取参考详情页的模块节奏：首屏吸引、核心卖点、细节特写、使用场景、结尾陈列。只学习结构，不复制文字、商品或品牌。",
    ratio: "9:16",
    scene: "卖点结构复刻",
    style: "原创电商",
  },
  {
    id: "minimal-detail-flow",
    title: "克制留白商详复刻",
    tag: "复刻商详",
    image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=88",
    productDescription: "适合百货、家居和数码类商品的干净详情页节奏。",
    prompt: "按参考图的留白、景别切换和材质展示节奏生成原创详情页套图，商品换成上传素材，画面内不生成可读文字。",
    ratio: "9:16",
    scene: "长图版式复刻",
    style: "克制留白",
  },
];

export const utilityImageCases: ImageWorkflowCase[] = [
  {
    id: "white-bg-clean",
    title: "纯净白底商品图",
    tag: "白底图",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=88",
    productDescription: "保留商品主体和自然接触阴影，生成平台可用白底图。",
    prompt: "保留商品真实轮廓、颜色、材质和关键细节，背景替换为纯净白底，阴影自然，不改变商品结构。",
    ratio: "1:1",
    scene: "电商白底",
    style: "真实光影",
  },
  {
    id: "ratio-expand",
    title: "电商留白扩图",
    tag: "比例调整",
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=88",
    productDescription: "在不改变主体的前提下扩展背景，适配平台比例。",
    prompt: "保持主体位置、比例和边缘自然，扩展外部背景，生成连续真实的电商留白画面。",
    ratio: "9:16",
    scene: "智能扩图",
    style: "电商留白",
  },
  {
    id: "hd-product",
    title: "商品细节高清优化",
    tag: "高清优化",
    image: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=900&q=88",
    productDescription: "修复商品边缘、材质、纹理和细节清晰度。",
    prompt: "增强图片清晰度、商品边缘和材质细节，降低噪点，保持真实自然，不改变商品款式和颜色。",
    ratio: "1:1",
    scene: "2 倍增强",
    style: "商品质感",
  },
];

export const whiteBackgroundCases = utilityImageCases.filter((item) => item.id === "white-bg-clean");
export const resizeImageCases = utilityImageCases.filter((item) => item.id === "ratio-expand");
export const hdEnhanceCases = utilityImageCases.filter((item) => item.id === "hd-product");

export const modelWearCases: ImageWorkflowCase[] = [
  {
    id: "commute-trench-wear",
    title: "通勤风衣上身图",
    tag: "模特穿搭",
    image: "https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=900&q=88",
    productDescription: "风衣、衬衫、阔腿裤等通勤服饰，强调版型、垂坠和日常上身效果。",
    prompt: "保持模特五官、发型和自然站姿，将商品自然穿在模特身上，衣服版型清晰，面料垂坠真实，背景为通勤街拍氛围。",
    ratio: "3:4",
    scene: "通勤街拍",
    style: "自然真实",
  },
  {
    id: "boutique-dress-wear",
    title: "精品店试穿穿搭",
    tag: "模特穿搭",
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=88",
    productDescription: "连衣裙、套装或女装单品，适合店铺模特展示图。",
    prompt: "生成精品店试穿效果，商品完整自然上身，保持模特比例协调，布料纹理和边缘清晰，画面有轻奢时尚感。",
    ratio: "9:16",
    scene: "精品店试穿",
    style: "轻奢时尚",
  },
  {
    id: "home-knit-wear",
    title: "居家针织自然穿搭",
    tag: "模特穿搭",
    image: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=900&q=88",
    productDescription: "针织衫、家居服、休闲裤等日常穿搭商品。",
    prompt: "让模特在自然居家环境中展示商品，动作放松，商品穿着贴合但不变形，整体清新日常，适合电商服饰主图。",
    ratio: "4:3",
    scene: "自然居家",
    style: "清新日常",
  },
];
