import { readFile } from "node:fs/promises";

const checks = [
  [
    "content review disabled by default",
    ".env.example",
    "CONTENT_REVIEW_ENABLED=false",
  ],
  [
    "upload becomes immediately ready",
    "app/api/uploads/confirm/route.ts",
    'status: "READY"',
  ],
  [
    "worker directly settles when review is disabled",
    "scripts/worker.mjs",
    "contentReviewEnabled ? await submitForReview(task, savedAssets) : await settleSuccess(task, savedAssets)",
  ],
  [
    "lifecycle releases historical pending outputs",
    "scripts/lifecycle-maintenance.mjs",
    "settleBypassedOutputTask",
  ],
  [
    "manual review cannot be overwritten by automation",
    "scripts/moderation-worker.mjs",
    'review.review_source === "MANUAL"',
  ],
  [
    "download READY gate",
    "app/api/assets/[id]/download/route.ts",
    "audit_status = 'READY'",
  ],
  [
    "task list avoids pending output URL",
    "app/api/tasks/list/route.ts",
    'task.status === "SUCCEEDED"',
  ],
  [
    "asset library separates uploads and saved generated results",
    "app/assets/page.tsx",
    'title: "已保存结果", assets: generatedAssets',
  ],
  [
    "asset thumbnails open media preview",
    "app/assets/page.tsx",
    '<button className="asset-media" type="button"',
  ],
  [
    "asset downloads remain explicit",
    "app/assets/page.tsx",
    "href={`/api/assets/${asset.id}/download/`}",
  ],
  [
    "ready generated assets can be reused as task inputs",
    "lib/task-creation.ts",
    "kind = 'OUTPUT' AND audit_status = 'READY'",
  ],
  [
    "administrator content assets entry",
    "app/admin/page.tsx",
    '<Link href="/assets"><Boxes',
  ],
  [
    "task outputs open media preview",
    "app/tasks/[id]/page.tsx",
    "setPreviewOutput(output)",
  ],
  [
    "image workflows show elapsed generation time",
    "app/components/image-workflow-page.tsx",
    "<GenerationProgress",
  ],
  [
    "AI image generation can submit without a source asset",
    "lib/product-config.ts",
    'key: "image-generate"',
    "minAssets: 0",
  ],
  [
    "AI image generation uses a dedicated case-board layout",
    "app/components/ai-image-generate-page.tsx",
    "yh-image-form-card",
    "yh-case-board",
  ],
  [
    "Product scene image uses the recreated case-board layout",
    "app/components/product-scene-image-page.tsx",
    "生成产品场景图",
    "yh-scene-case-board",
  ],
  [
    "Product scene image task accepts multiple product images",
    "app/api/tasks/scene/route.ts",
    "body.assetIds",
    "slice(0, 5)",
  ],
  [
    "Image workflows expose case references and same-style apply",
    "app/components/image-workflow-page.tsx",
    "案例参考",
    "做同款",
  ],
  [
    "model wear shows elapsed generation time",
    "app/create/model-wear/page.tsx",
    "<GenerationProgress",
  ],
  [
    "product ad video shows staged progress",
    "app/components/product-ad-video-page.tsx",
    "<VideoGenerationProgress",
  ],
  [
    "product ad video exposes right-side video case references",
    "app/components/product-ad-video-page.tsx",
    "ad-case-board",
    "做同款",
  ],
  [
    "product ad video same-style cases refill generation parameters",
    "app/components/product-ad-video-page.tsx",
    "applyCase",
    "setSpecialRequirements",
  ],
  [
    "product ad video case media opens a detail dialog",
    "app/components/product-ad-video-page.tsx",
    "ad-case-dialog",
    "setDetailCase(item)",
  ],
  [
    "product ad video same-style cases include a hidden internal prompt",
    "app/components/product-ad-video-page.tsx",
    "internalPrompt",
    "内置策略",
  ],
  [
    "video workflows show staged progress",
    "app/components/video-workflow-page.tsx",
    "<VideoGenerationProgress",
  ],
  [
    "recreate video shows staged progress",
    "app/features/recreate-video/components/panels/generate-panel.tsx",
    "<VideoGenerationProgress",
  ],
  [
    "recreate video accepts Douyin links",
    "app/features/recreate-video/hooks/use-recreate-source.ts",
    'fetch("/api/imports/douyin/"',
  ],
  [
    "Douyin imports enforce a 15 second limit",
    "lib/douyin-import.ts",
    "DOUYIN_MAX_DURATION_SECONDS = 15",
  ],
  [
    "Douyin imports support server-validated time ranges",
    "lib/douyin-import.ts",
    "--download-sections",
  ],
  [
    "Recreate video keeps an ordered Douyin clip collection",
    "app/components/recreate-video-page.tsx",
    "douyinClips",
  ],
  [
    "Recreate video hands clips to video mix",
    "app/components/recreate-video-page.tsx",
    "aigc-video-mix-asset-ids",
  ],
  [
    "Recreate video saves account drafts",
    "app/features/recreate-video/api.ts",
    'fetch("/api/workflow-drafts/"',
  ],
  [
    "Recreate video shows saved project list",
    "app/components/recreate-video-page.tsx",
    "visibleDrafts = useMemo(() => serverDrafts.slice(0, 8)",
  ],
  [
    "Recreate video local draft preserves server id across refresh",
    "app/components/recreate-video-page.tsx",
    "__serverDraftId",
  ],
  [
    "Recreate video does not auto-create server projects",
    "app/components/recreate-video-page.tsx",
    "!account || !draftId || !draftHasContent(draft)",
  ],
  [
    "Recreate video requires a user project name before saving",
    "app/components/recreate-video-page.tsx",
    "请先填写项目名称",
  ],
  [
    "Recreate video requires a project before submit",
    "app/components/recreate-video-page.tsx",
    "请先创建项目，再提交生成任务",
  ],
  [
    "Recreate video starts from an explicit project gate",
    "app/components/recreate-video-page.tsx",
    "RecreateProjectGate",
  ],
  [
    "Recreate video drops anonymous local drafts",
    "app/components/recreate-video-page.tsx",
    "!isUuid(draft.__serverDraftId)",
  ],
  [
    "Recreate video restores project task progress",
    "app/components/recreate-video-page.tsx",
    "restoreProjectTask",
  ],
  [
    "Recreate video supports previous step navigation",
    "app/components/recreate-video-page.tsx",
    "goPreviousStep",
  ],
  [
    "Recreate video requires selected keyframes before replacement",
    "app/components/recreate-video-page.tsx",
    "selectedKeyframes.length >= 4",
  ],
  [
    "Recreate video has a simplified three-step workflow",
    "app/features/recreate-video/constants.ts",
    "素材与提示词",
  ],
  [
    "Recreate video auto-extracts keyframes after source selection",
    "app/components/recreate-video-page.tsx",
    "prepareSourceReferenceAndContinue",
  ],
  [
    "Recreate video frame endpoint can skip AI analysis",
    "app/api/workflows/recreate-video-analysis/route.ts",
    'body.mode === "frames"',
  ],
  [
    "Recreate video product step shows prompt and material workflow",
    "app/features/recreate-video/components/panels/materials-panel.tsx",
    "素材与提示词",
  ],
  [
    "Recreate video product step optimizes prompts",
    "app/features/recreate-video/components/panels/materials-panel.tsx",
    "优化提示词",
  ],
  [
    "Recreate video includes a built-in remake prompt",
    "app/features/recreate-video/prompts.ts",
    "builtInRecreatePrompt",
  ],
  [
    "Recreate video built-in prompt maps uploaded models to original actions",
    "app/features/recreate-video/prompts.ts",
    "必须用该新模特替换原视频中的真人主体",
  ],
  [
    "Recreate video keeps internal strategy out of visible steps",
    "app/components/recreate-video-page.tsx",
    'step === "generate" && generatePanel',
  ],
  [
    "Recreate video material tags can be referenced in commands",
    "app/features/recreate-video/components/panels/materials-panel.tsx",
    "recreate-material-tags",
  ],
  [
    "Recreate video material tags support @ mentions",
    "app/features/recreate-video/components/panels/materials-panel.tsx",
    "recreate-mention-menu",
  ],
  [
    "Recreate video can convert portraits to per-material multi-view references",
    "app/features/recreate-video/components/panels/materials-panel.tsx",
    "人物多视图",
  ],
  [
    "Recreate video keeps material processing on each uploaded item",
    "app/features/recreate-video/components/panels/materials-panel.tsx",
    "recreate-selected-images",
  ],
  [
    "Recreate video material cards can create reusable references",
    "app/features/recreate-video/components/panels/materials-panel.tsx",
    "素材多视图",
  ],
  [
    "Recreate video lets users actively tag material kind",
    "app/features/recreate-video/components/panels/materials-panel.tsx",
    "recreate-material-kind-select",
  ],
  [
    "Recreate video material kind selector includes model product and scene",
    "app/features/recreate-video/components/panels/materials-panel.tsx",
    "<option value=\"scene\">场景",
  ],
  [
    "Recreate video person multi-view prompt keeps full body instead of clothing only",
    "app/components/recreate-video-page.tsx",
    "禁止输出单件服装多视图",
  ],
  [
    "Recreate video person multi-view prompt can complete clothing into a full model",
    "app/components/recreate-video-page.tsx",
    "即使输入图只有裙子、衣服或局部穿搭，也必须补全为完整虚拟真人模特",
  ],
  [
    "Recreate video person multi-view prompt locks the full person as subject",
    "app/components/recreate-video-page.tsx",
    "必须把“完整人物/模特”作为唯一主主体",
  ],
  [
    "Recreate reference worker locks person scene to full body subject",
    "scripts/worker.mjs",
    "必须把“完整人物”作为唯一主主体来提取和重建",
  ],
  [
    "Recreate video person multi-view prompt keeps face contour before masking",
    "app/components/recreate-video-page.tsx",
    "第一步必须先生成完整头部和完整脸部轮廓",
  ],
  [
    "Recreate video person prompt uses a real studio contact sheet",
    "app/components/recreate-video-page.tsx",
    "真实摄影棚多机位试衣参考图",
  ],
  [
    "Recreate video person prompt requires auxiliary side and back views",
    "app/components/recreate-video-page.tsx",
    "背面全身、侧面全身、3/4 角度全身",
  ],
  [
    "Recreate reference worker generates a real studio contact sheet",
    "scripts/worker.mjs",
    "真实摄影棚多机位试衣参考图",
  ],
  [
    "Recreate reference worker requires realistic human photo style",
    "scripts/worker.mjs",
    "真实皮肤纹理、真实布料、自然站姿",
  ],
  [
    "Recreate reference worker requires face close-up studies",
    "scripts/worker.mjs",
    "脸部/头部近景控制在 2-3 个即可",
  ],
  [
    "Recreate reference worker asks face close-ups to mask different parts",
    "scripts/worker.mjs",
    "部分只做很轻的局部隐私遮挡",
  ],
  [
    "Recreate reference worker preserves input face structure",
    "scripts/worker.mjs",
    "以输入人物脸部结构和五官相对位置为强参考",
  ],
  [
    "Recreate reference workflow returns one identity board output",
    "lib/product-config.ts",
    "outputsPerTask: 1",
  ],
  [
    "Recreate reference workflow is powered by Google image credentials",
    "lib/product-config.ts",
    "GOOGLE_AI_API_KEY || process.env.GEMINI_API_KEY || process.env.NANO_BANANA_API_KEY",
  ],
  [
    "Worker routes recreate references to Nano Banana image generation with fallback",
    "scripts/worker.mjs",
    "createGeminiImageWithSophnetFallback(inputUrls, prompt, generationTaskId, index, input.aspectRatio)",
  ],
  [
    "Gemini image generation falls back to SophNet when configured",
    "scripts/worker.mjs",
    "gemini_image_fallback_to_sophnet",
  ],
  [
    "Gemini image generation asks for text and image modalities",
    "scripts/worker.mjs",
    'responseModalities: ["TEXT", "IMAGE"]',
  ],
  [
    "Gemini image generation supports a configurable relay endpoint",
    "scripts/worker.mjs",
    "GOOGLE_AI_BASE_URL",
  ],
  [
    "Gemini response format receives enum aspect ratio values",
    "scripts/worker.mjs",
    "ASPECT_RATIO_SIXTEEN_BY_NINE",
  ],
  [
    "Worker keeps AI image generation prompt-only instead of product-main-image bias",
    "scripts/worker.mjs",
    'workflowKey === "image-generate"',
    "按提示词生成原创图像",
  ],
  [
    "Gemini image generation supports a worker-only proxy",
    "scripts/worker.mjs",
    "GOOGLE_AI_PROXY_URL",
  ],
  [
    "Gemini proxy support uses undici ProxyAgent",
    "scripts/worker.mjs",
    "new ProxyAgent(proxyUrl)",
  ],
  [
    "Gemini image generation parses inline image data",
    "scripts/worker.mjs",
    "inlineData || imagePart?.inline_data",
  ],
  [
    "Recreate video face mask fallback does not cover landscape identity boards",
    "app/components/recreate-video-page.tsx",
    "canvas.width < canvas.height ? fallbackFaceRegions",
  ],
  [
    "Recreate reference worker avoids heavy face masks during generation",
    "scripts/worker.mjs",
    "不要用粗重马赛克或大面积白条破坏真实感",
  ],
  [
    "Recreate video product multi-view prompt must not turn clothing stills into models",
    "app/components/recreate-video-page.tsx",
    "如果输入是服装静物且用户选择了商品类型，则输出服装商品多视图；不要补成人物模特",
  ],
  [
    "Recreate video material multi-view uses a dedicated reference image workflow",
    "app/components/recreate-video-page.tsx",
    "/api/tasks/recreate-reference/",
  ],
  [
    "Recreate reference workflow avoids product-scene prompt bias",
    "scripts/worker.mjs",
    "不要套用普通商品主图逻辑",
  ],
  [
    "Recreate reference workflow is exposed by API route",
    "app/api/tasks/recreate-reference/route.ts",
    "recreateReferenceWorkflow",
  ],
  [
    "Recreate video material analysis prioritizes worn clothing as person",
    "app/api/workflows/recreate-material-analysis/route.ts",
    "只要图片中能看到完整人体、人体轮廓、穿着服装的人、模特试穿效果，就必须优先判为 person",
  ],
  [
    "Recreate video material module supports product multi-view references",
    "app/features/recreate-video/components/panels/materials-panel.tsx",
    "素材多视图",
  ],
  [
    "Recreate video material module supports scene multi-view references",
    "app/features/recreate-video/components/panels/materials-panel.tsx",
    "场景多视图",
  ],
  [
    "Recreate video material images open a zoom preview",
    "app/components/recreate-video-page.tsx",
    "setPreviewMedia({ url, name, mimeType: \"image/*\" })",
  ],
  [
    "Recreate video can create motion-structure reference videos",
    "app/components/recreate-video-page.tsx",
    "动作结构参考视频",
  ],
  [
    "Recreate video compliant reference mode calls the sanitize endpoint",
    "app/features/recreate-video/api.ts",
    "/api/workflows/recreate-video-sanitize/",
  ],
  [
    "Recreate video sanitize endpoint creates edge motion video and meets Ark pixel floor",
    "app/api/workflows/recreate-video-sanitize/route.ts",
    "edge-motion-structure-no-audio-minimum-ark-resolution-time-compressed",
  ],
  [
    "Recreate video sanitize endpoint compresses long references instead of clipping",
    "app/api/workflows/recreate-video-sanitize/route.ts",
    "setpts=PTS/${speed.toFixed(6)}",
  ],
  [
    "Recreate video sanitize endpoint outputs at least 720p reference video",
    "app/api/workflows/recreate-video-sanitize/route.ts",
    "width: 720, height: 1280",
  ],
  [
    "Recreate video supports deterministic face mask strengthening",
    "app/components/recreate-video-page.tsx",
    "强化脸部遮盖",
  ],
  [
    "Recreate video face mask strengthening overlays a grid",
    "app/components/recreate-video-page.tsx",
    "privacy-masked-multiview.jpg",
  ],
  [
    "Recreate video face mask strengthening uses detected face regions first",
    "app/components/recreate-video-page.tsx",
    "analyzeFaceMaskRegions(source.assetId)",
  ],
  [
    "Recreate video face mask analysis endpoint calls SophNet",
    "app/api/workflows/recreate-face-mask-analysis/route.ts",
    "recreate_face_mask_analysis",
  ],
  [
    "Recreate video face mask analysis returns normalized face regions",
    "app/api/workflows/recreate-face-mask-analysis/route.ts",
    "faceRegions",
  ],
  [
    "Recreate video material analysis endpoint calls SophNet",
    "app/api/workflows/recreate-material-analysis/route.ts",
    "recreate_material_analysis",
  ],
  [
    "Recreate video privacy multi-view prompt masks face identity",
    "app/components/recreate-video-page.tsx",
    "生成完成后由系统二次做极轻微模糊",
  ],
  [
    "Recreate video submits keyframe collage as a reference image",
    "app/features/recreate-video/hooks/use-recreate-keyframes.ts",
    "createKeyframeCollageAsset",
  ],
  [
    "Recreate video keyframe collage is converted to a motion structure board before Ark",
    "app/features/recreate-video/hooks/use-recreate-keyframes.ts",
    "recreate-motion-structure-collage.jpg",
  ],
  [
    "Recreate video keyframe collage uses Sobel edges instead of raw frames",
    "app/features/recreate-video/hooks/use-recreate-keyframes.ts",
    "Math.sqrt(gx * gx + gy * gy)",
  ],
  [
    "Recreate video submits reference video before keyframe collage",
    "app/components/recreate-video-page.tsx",
    "referenceVideoAssetId",
  ],
  [
    "Recreate video prompt asks model to time-compress full motion",
    "app/components/recreate-video-page.tsx",
    "按比例压缩完整舞蹈/手势/走位段落",
  ],
  [
    "Recreate video imports full Douyin references for sanitize compression",
    "app/components/recreate-video-page.tsx",
    "cacheId: douyinAnalysis.cacheId",
  ],
  [
    "Douyin full reference import can exceed Ark task duration before sanitize",
    "lib/douyin-import.ts",
    "clip.isFullVideo",
  ],
  [
    "Recreate video keyframe collage falls back to video capture",
    "app/features/recreate-video/hooks/use-recreate-keyframes.ts",
    "captureVideoFrameForCanvas(sourceSelection.preview, frame.time)",
  ],
  [
    "Recreate video extracted keyframe URLs last through long editing sessions",
    "app/api/workflows/recreate-video-analysis/route.ts",
    "24 * 3600",
  ],
  [
    "Recreate video prompt identifies the submitted keyframe collage",
    "app/features/recreate-video/prompts.ts",
    "第${collageImageIndex}张参考图是一张由已选关键画面转换成边缘轮廓线稿的动作结构板",
  ],
  [
    "Recreate video analysis asks for frame-by-frame action timeline",
    "app/api/workflows/recreate-video-analysis/route.ts",
    "actionTimeline 是给视频生成模型看的逐帧动作导演脚本",
  ],
  [
    "Recreate video submit auto-analyzes action continuity before generation",
    "app/components/recreate-video-page.tsx",
    "正在分析关键帧动作连续性",
  ],
  [
    "Recreate video final prompt includes the action director script",
    "app/features/recreate-video/prompts.ts",
    "【逐帧动作导演脚本】",
  ],
  [
    "Recreate video final step hides duplicate prompt fields",
    "app/features/recreate-video/components/panels/generate-panel.tsx",
    "提示词、素材和参考画面会自动合并",
  ],
  [
    "Recreate video worker has a backend remake director fallback",
    "scripts/worker.mjs",
    "内置复刻导演指令",
  ],
  [
    "Recreate video worker can drop rejected system collage and retry",
    "scripts/worker.mjs",
    "privacyCollageContentIndex",
  ],
  [
    "Recreate video task allows one system keyframe collage image",
    "app/api/tasks/recreate-video/route.ts",
    "系统会额外提交一张十二宫格参考图",
  ],
  [
    "Recreate video prompt polish endpoint uses SophNet",
    "app/api/workflows/recreate-video-analysis/route.ts",
    'body.mode === "polish"',
  ],
  [
    "Recreate video prompt polish receives material labels",
    "app/api/workflows/recreate-video-analysis/route.ts",
    "materialLabels",
  ],
  [
    "Recreate video no longer forces forward navigation",
    "app/components/recreate-video-page.tsx",
    "workflowSteps.findIndex((item) => item.key === step) > unlockedIndex",
  ],
  [
    "Workflow drafts list active saved projects",
    "app/api/workflow-drafts/route.ts",
    "status IN ('ACTIVE', 'ARCHIVED')",
  ],
  [
    "Workflow drafts reject duplicate project titles",
    "app/api/workflow-drafts/route.ts",
    "DUPLICATE_PROJECT_TITLE",
  ],
  [
    "Workflow draft rename endpoint keeps duplicate title guard",
    "app/api/workflow-drafts/[id]/route.ts",
    "PROJECT_RENAMED",
  ],
  [
    "Project gate list exposes rename actions",
    "app/create/project/page.tsx",
    "重命名项目",
  ],
  [
    "Creation tools enter through the project gate",
    "app/tools/page.tsx",
    "projectGateHref(tool.workflowKey)",
  ],
  [
    "Image creation center uses Yinghai-style grouped tool cards",
    "app/tools/page.tsx",
    "yh-tools-card",
  ],
  [
    "Image creation center exposes the AI creative image section",
    "app/tools/page.tsx",
    "AI创意生图",
  ],
  [
    "App shell exposes the new top-level creation navigation",
    "app/components/app-shell.tsx",
    "灵感工作站",
  ],
  [
    "Video center expands every video module instead of hiding them in tabs",
    "app/components/video-center-page.tsx",
    "video-center-groups",
    "videoModules.map((module)",
  ],
  [
    "Task center warns users that task outputs are temporary",
    "app/tasks/page.tsx",
    "本站仅保留 48 小时",
  ],
  [
    "Asset library explains that task outputs must be manually saved",
    "app/assets/page.tsx",
    "任务结果需要手动加入素材库",
  ],
  [
    "Task outputs can be saved to the asset library on demand",
    "app/api/tasks/[id]/save-assets/route.ts",
    "TASK_OUTPUTS_SAVED_TO_LIBRARY",
  ],
  [
    "New worker outputs are temporary before library save",
    "scripts/worker.mjs",
    "TEMPORARY_OUTPUT",
  ],
  [
    "Lifecycle maintenance removes expired temporary task outputs",
    "scripts/lifecycle-maintenance.mjs",
    "cleanupExpiredTaskOutputs",
  ],
  [
    "Lifecycle maintenance records expired task outputs on the task",
    "scripts/lifecycle-maintenance.mjs",
    "expiredAssets",
  ],
  [
    "Expired task detail clearly explains that output files are gone",
    "app/tasks/[id]/page.tsx",
    "结果文件已过期",
  ],
  [
    "Expired task detail keeps the project continuation entry",
    "app/tasks/[id]/page.tsx",
    "回到项目继续编辑",
  ],
  [
    "Expired successful tasks can be regenerated from retained inputs",
    "app/api/tasks/[id]/retry/route.ts",
    "TASK_REGENERATED",
  ],
  [
    "Task detail exposes retained input parameters after outputs expire",
    "app/tasks/[id]/page.tsx",
    "保留的输入参数",
  ],
  [
    "Project gate keeps existing query params when opening projects",
    "lib/project-workflows.ts",
    "appendProjectId",
  ],
  [
    "Project gate page creates named projects before entering workflows",
    "app/create/project/page.tsx",
    "创建项目并开始",
  ],
  [
    "Direct image creation pages require a project",
    "app/create/product-hero/page.tsx",
    "ProjectRequiredGate",
  ],
  [
    "Direct AI image generation page requires a project",
    "app/create/image-generate/page.tsx",
    "ProjectRequiredGate",
  ],
  [
    "Direct recreate video page requires a project",
    "app/create/recreate-video/page.tsx",
    "ProjectRequiredGate",
  ],
  [
    "Recreate video header replaces manual save with rename",
    "app/components/recreate-video-page.tsx",
    "renameCurrentProject",
  ],
  [
    "Recreate video header shows the current project rename toolbar",
    "app/components/recreate-video-page.tsx",
    "recreate-project-toolbar",
  ],
  [
    "Project guard preserves deep-link query params",
    "app/components/project-required-gate.tsx",
    "query ? `?${query}` : \"\"",
  ],
  [
    "Workflow drafts hide exact duplicate payloads",
    "app/api/workflow-drafts/route.ts",
    "duplicate_rank = 1",
  ],
  [
    "Workflow drafts restore archived projects on save",
    "app/api/workflow-drafts/route.ts",
    "archived_at = NULL",
  ],
  [
    "Workflow drafts persist to database",
    "scripts/migrate.mjs",
    "CREATE TABLE IF NOT EXISTS workflow_drafts",
  ],
  [
    "Workflow draft events persist project input history",
    "scripts/migrate.mjs",
    "CREATE TABLE IF NOT EXISTS workflow_draft_events",
  ],
  [
    "Workflow draft saves write project event logs",
    "app/api/workflow-drafts/route.ts",
    "PROJECT_AUTOSAVED",
  ],
  [
    "Generated tasks keep source project visible",
    "lib/task-creation.ts",
    "SET status = 'ACTIVE', task_id = $4, archived_at = NULL, updated_at = NOW()",
  ],
  [
    "Generated tasks write project submission logs",
    "lib/task-creation.ts",
    "TASK_SUBMITTED",
  ],
  [
    "Assets store content hashes for dedupe",
    "scripts/migrate.mjs",
    "ALTER TABLE assets ADD COLUMN IF NOT EXISTS content_hash TEXT",
  ],
  [
    "Upload presign reuses duplicate ready assets",
    "app/api/uploads/presign/route.ts",
    "ASSET_UPLOAD_DEDUPED",
  ],
  [
    "Recreate uploads send SHA-256 content hashes",
    "app/features/recreate-video/api.ts",
    "const contentHash = await sha256Hex(item.file)",
  ],
  [
    "Video mix accepts an ordered dynamic material list",
    "app/components/video-workflow-page.tsx",
    "mixUploads",
  ],
  [
    "Video worker can resume running tasks after restart",
    "scripts/worker.mjs",
    "status IN ('QUEUED', 'RUNNING')",
  ],
  [
    "Ark video timeout is configurable",
    "scripts/worker.mjs",
    "ARK_VIDEO_TIMEOUT_MS",
  ],
  [
    "Video center exposes the model spokesperson module",
    "app/features/video-center/modules.ts",
    "/create/model-spokesperson-video",
  ],
  [
    "Video center labels model spokesperson as product director workflow",
    "app/features/video-center/modules.ts",
    "商品口播导演",
    "文案工作台",
  ],
  [
    "Model spokesperson page exposes case references and same-style backfill",
    "app/components/model-spokesperson-script-page.tsx",
    "spokespersonCases",
    "做同款",
  ],
  [
    "Model spokesperson case references are right-side contextual content",
    "app/components/model-spokesperson-script-page.tsx",
    "showCaseReferences",
    "spokesperson-context-thumbs",
  ],
  [
    "Model spokesperson plans include story arcs and action beats",
    "app/api/workflows/model-spokesperson-script/route.ts",
    "storyArc",
    "actionBeats",
  ],
  [
    "Model spokesperson plans consume director brief",
    "app/api/workflows/model-spokesperson-script/route.ts",
    "directorBrief",
    "导演问答/商品理解",
  ],
  [
    "Model spokesperson repairs incomplete LLM plan JSON",
    "app/api/workflows/model-spokesperson-script/route.ts",
    "model_spokesperson_script_plans_repair",
    "plansRepairPrompt",
  ],
  [
    "Model spokesperson allows minimal product input",
    "app/api/workflows/model-spokesperson-script/route.ts",
    "请至少上传商品图，或填写商品名称/一句话描述",
    "用户上传商品",
  ],
  [
    "Model spokesperson can auto-recognize product director brief from images",
    "app/api/workflows/model-spokesperson-script/route.ts",
    "model_spokesperson_director_brief",
    "image_url",
  ],
  [
    "Model spokesperson supports iterative director chat",
    "app/api/workflows/model-spokesperson-script/route.ts",
    "model_spokesperson_director_chat",
    "quickReplies",
    "readyToGenerate",
  ],
  [
    "Model spokesperson exposes director chat UI",
    "app/components/model-spokesperson-script-page.tsx",
    "AI 导演对话",
    "runDirectorChat",
    "directorMessages",
  ],
  [
    "Model spokesperson product multiview ignores ad scenes",
    "app/components/model-spokesperson-script-page.tsx",
    "只生成同一款真实商品本体参考板",
    "不要放入客厅、厨房、办公室、户外、租房、展会",
  ],
  [
    "Model spokesperson plan UI exposes story and action beats",
    "app/components/model-spokesperson-script-page.tsx",
    "spokesperson-plan-story",
    "spokesperson-plan-beats",
  ],
  [
    "Model spokesperson restores legacy plan summaries safely",
    "app/components/model-spokesperson-script-page.tsx",
    "splitSummaryPoints",
    "normalizeDraftPlan",
    "normalizeActionBeatText",
    "normalizeScriptResult",
    "normalizeVideoPack",
    "normalizeDirectorMessages",
    "normalizeProductImages",
    "normalizeStageAssets",
    "normalizeStageAsset",
  ],
  [
    "Model spokesperson route wraps search params in suspense",
    "app/create/model-spokesperson-video/page.tsx",
    "<Suspense",
    "ProjectRequiredGate",
  ],
  [
    "Model spokesperson UI exposes auto product recognition",
    "app/components/model-spokesperson-script-page.tsx",
    "自动识别/推荐",
    "analyzeDirectorBrief",
  ],
  [
    "Model spokesperson exposes director question controls",
    "app/components/model-spokesperson-script-page.tsx",
    "商品导演问答",
    "人物参与",
  ],
  [
    "Model spokesperson hides director recommendation chip rows",
    "app/components/model-spokesperson-script-page.tsx",
    "productUnderstanding",
    "peopleModeOptions",
  ],
  [
    "Model spokesperson uses a step-by-step workflow UI",
    "app/components/model-spokesperson-script-page.tsx",
    "spokesperson-workflow-steps",
    "1 商品理解",
    "4 提交视频",
  ],
  [
    "Model spokesperson supports product-only scene director mode",
    "app/components/model-spokesperson-script-page.tsx",
    "场景导演参考",
    "用户选择无真人",
  ],
  [
    "Model spokesperson video pack consumes selected plan story",
    "app/api/workflows/model-spokesperson-script/route.ts",
    "方案故事弧线",
    "方案动作节拍",
  ],
  [
    "Video center exposes recreate inside the smart commerce group",
    "app/features/video-center/modules.ts",
    'key: "smart-commerce"',
    "复刻爆款带货视频-新版",
  ],
  [
    "Model spokesperson includes a hidden video task pack and submit action",
    "app/components/model-spokesperson-script-page.tsx",
    "生成并提交视频",
    "内部任务包会自动合并",
  ],
  [
    "Model spokesperson video routes through Ark video generation",
    "scripts/worker.mjs",
    '"model-spokesperson-video", "video-mix"',
  ],
  [
    "Model spokesperson blocks non-video outputs from video preview",
    "app/components/model-spokesperson-script-page.tsx",
    "任务返回了非视频素材",
  ],
  [
    "Model spokesperson exposes staged debug generation",
    "app/components/model-spokesperson-script-page.tsx",
    "分阶段素材",
  ],
  [
    "Model spokesperson masks generated model reference",
    "app/components/model-spokesperson-script-page.tsx",
    "已遮挡模特参考",
  ],
  [
    "Model spokesperson keeps human reference images out of Ark submit",
    "app/components/model-spokesperson-script-page.tsx",
    "审核安全提交策略",
  ],
  [
    "Model spokesperson avoids in-video subtitles",
    "app/components/model-spokesperson-script-page.tsx",
    "不要在画面中生成字幕",
  ],
  [
    "Model spokesperson storyboard image avoids subtitles",
    "app/components/model-spokesperson-script-page.tsx",
    "口播内容只作为内部节奏绑定，不能画进分镜图",
  ],
  [
    "Model spokesperson storyboard locks 4x3 reading order",
    "app/components/model-spokesperson-script-page.tsx",
    "第一行是第1-4格",
    "第三行是第9-12格",
  ],
  [
    "Model spokesperson storyboard forbids visible frame numbers",
    "app/components/model-spokesperson-script-page.tsx",
    "禁止在图像中写任何数字、序号、角标",
  ],
  [
    "Model spokesperson storyboard uses scene and story intent",
    "app/api/workflows/model-spokesperson-script/route.ts",
    "scene、intent、visual、camera",
    "一条有情节的 15 秒小广告",
  ],
  [
    "Model spokesperson exposes audio generation toggle",
    "app/components/model-spokesperson-script-page.tsx",
    "生成讲解声音",
  ],
  [
    "Model spokesperson passes audio option to tasks",
    "app/api/tasks/model-spokesperson-video/route.ts",
    "generateAudio: body.generateAudio !== false",
  ],
  [
    "Model spokesperson backend enforces no-person video mode",
    "app/api/tasks/model-spokesperson-video/route.ts",
    "用户已选择无真人模式",
    "peopleMode",
  ],
  [
    "Ark video generation honors audio option",
    "scripts/worker.mjs",
    "generate_audio: input.generateAudio !== false",
  ],
  [
    "Model spokesperson stage images open a preview modal",
    "app/components/model-spokesperson-script-page.tsx",
    "spokesperson-preview-modal",
  ],
  [
    "Model spokesperson exposes model source controls",
    "app/components/model-spokesperson-script-page.tsx",
    "模特来源",
    "上传模特",
    "资产库",
  ],
  [
    "Model spokesperson persists selected model source in drafts",
    "app/components/model-spokesperson-script-page.tsx",
    "modelSourceMode",
    "modelSource",
  ],
  [
    "Model spokesperson uses selected model source for reference generation",
    "app/components/model-spokesperson-script-page.tsx",
    "modelSource?.assetId || stageAssets.productMultiview?.assetId",
  ],
  [
    "Model spokesperson model prompt requires realistic contact sheet output",
    "app/components/model-spokesperson-script-page.tsx",
    "真实摄影棚多机位试衣参考图",
    "不能是动漫、插画、手绘、3D 渲染",
  ],
  [
    "Video tasks keep long director prompts",
    "lib/task-creation.ts",
    "workflow.key.includes(\"video\") ? 5000 : 1200",
  ],
  [
    "Model spokesperson scripts are server generated and rate limited",
    "app/api/workflows/model-spokesperson-script/route.ts",
    "spokesperson-script:attempts",
  ],
  [
    "Model spokesperson pack generation is LLM backed",
    "app/api/workflows/model-spokesperson-script/route.ts",
    "model_spokesperson_video_pack",
    "normalizePack",
  ],
  [
    "Douyin import only accepts allowlisted hosts",
    "lib/douyin-import.ts",
    "hostname.endsWith(`.${domain}`)",
  ],
  [
    "Douyin import installs browser impersonation support",
    "scripts/install-yt-dlp.sh",
    "yt-dlp[default,curl-cffi]",
  ],
  [
    "Douyin import can reuse a headless browser profile",
    "lib/douyin-import.ts",
    'args.push("--cookies-from-browser"',
  ],
  [
    "Douyin analyze creates temporary source cache",
    "app/api/imports/douyin/route.ts",
    "createSourceCache",
  ],
  [
    "Douyin import can reuse temporary cache",
    "app/api/imports/douyin/route.ts",
    "importCachedDouyinVideo",
  ],
  [
    "Douyin temporary caches expire through lifecycle",
    "scripts/lifecycle-maintenance.mjs",
    "cleanupExpiredDouyinCaches",
  ],
  [
    "Recreate video previews cached Douyin source",
    "app/features/recreate-video/components/panels/source-panel.tsx",
    "原视频临时预览",
  ],
  [
    "Recreate video hides multi-frame extraction details from source step",
    "app/features/recreate-video/components/panels/source-panel.tsx",
    "下一步会自动准备参考画面",
  ],
  [
    "Recreate video analysis extracts frames",
    "app/api/workflows/recreate-video-analysis/route.ts",
    "ffmpeg",
  ],
  [
    "Recreate video analysis calls SophNet Chat",
    "app/api/workflows/recreate-video-analysis/route.ts",
    "chat/completions",
  ],
  [
    "Expired Douyin cache cleanup removes frame images",
    "scripts/lifecycle-maintenance.mjs",
    "frameStorageKeys",
  ],
  [
    "Douyin search modal links become work links",
    "lib/douyin-import.ts",
    "modal_id",
  ],
  [
    "Douyin rejects non-work detail pages early",
    "lib/douyin-import.ts",
    "UNSUPPORTED_DOUYIN_PAGE",
  ],
  [
    "content rejection refund",
    "app/api/admin/reviews/[id]/route.ts",
    "CONTENT_REJECTED",
  ],
  ["server-side revocable sessions", "lib/session.ts", "login_sessions"],
  ["login failure limit", "app/api/auth/login/route.ts", "LOGIN_RATE_LIMITED"],
  [
    "task cancellation refund",
    "app/api/tasks/[id]/cancel/route.ts",
    "USER_CANCELED",
  ],
  [
    "lifecycle review timeout",
    "scripts/lifecycle-maintenance.mjs",
    "OUTPUT_REVIEW_TIMEOUT",
  ],
  [
    "deployment runs lifecycle maintenance",
    "scripts/deploy.sh",
    "systemctl start aigc-lifecycle-maintenance.service",
  ],
  [
    "account deletion finalization",
    "scripts/lifecycle-maintenance.mjs",
    "ACCOUNT_DELETION_FINALIZED",
  ],
  [
    "WeChat Native accepts code_url without prepay_id",
    "lib/wechat-pay.ts",
    "if (!response.ok || !payload?.code_url)",
  ],
  [
    "administrator login redirect",
    "app/api/auth/login/route.ts",
    'administrator ? "/admin" : "/workspace"',
  ],
  [
    "recharge code transaction lock",
    "app/api/recharge-codes/redeem/route.ts",
    "FOR UPDATE",
  ],
  [
    "recharge code idempotent ledger",
    "app/api/recharge-codes/redeem/route.ts",
    "recharge-code:${code.id}:${user.id}",
  ],
  [
    "production acceptance account bootstrap",
    "scripts/deploy.sh",
    "configure-production-acceptance.mjs",
  ],
  [
    "production acceptance review cleanup",
    "scripts/configure-production-acceptance.mjs",
    "ACCEPTANCE_CLEANUP",
  ],
  [
    "production recharge code acceptance",
    "scripts/ark-video-acceptance.mjs",
    "duplicate denial and disable",
  ],
  ["structured task logging", "scripts/worker.mjs", "task_started"],
  ["request correlation", "lib/task-creation.ts", "request_id"],
  ["administrator exempt billing", "lib/task-creation.ts", "ADMIN_EXEMPT_TASK"],
  [
    "administrator exempt failure settlement",
    "scripts/worker.mjs",
    'billingMode === "ADMIN_EXEMPT"',
  ],
  [
    "administrator exempt UI label",
    "app/components/app-shell.tsx",
    "管理员免积分",
  ],
  [
    "administrator exempt production acceptance",
    "scripts/admin-exempt-acceptance.mjs",
    "final wallet and ADMIN_EXEMPT_TASK audit",
  ],
  [
    "product hero production acceptance",
    "scripts/product-hero-acceptance.mjs",
    "real SophNet create/query/download protocol",
  ],
  [
    "real user product hero production acceptance",
    "scripts/real-user-product-hero-acceptance.mjs",
    "official recharge-code credit",
  ],
  [
    "real user account production preflight",
    "scripts/real-user-account-preflight.mjs",
    "publicEmailRegistration",
  ],
  ["SophNet provider logs", "scripts/worker.mjs", "create_image_task"],
  [
    "SophNet production preflight",
    "scripts/production-preflight.mjs",
    "SophNet access: OK",
  ],
  [
    "acceptance notification suppression",
    "scripts/worker.mjs",
    "notification_suppressed",
  ],
  [
    "routine task success email disabled by default",
    "lib/notifications.ts",
    'EMAIL_NOTIFY_TASK_SUCCEEDED !== "true"',
  ],
  [
    "wallet shows successful frozen-point settlement",
    "app/api/wallet/route.ts",
    "从冻结积分中正式扣除",
  ],
  [
    "direct email suppression",
    "lib/email.ts",
    "isNotificationRecipientSuppressed",
  ],
  [
    "systemd web failure alert",
    "deploy/aigc-web.service",
    "OnFailure=aigc-alert@%n.service",
  ],
  [
    "health timer production environment",
    "deploy/aigc-health-alert.service",
    "EnvironmentFile=-/home/ubuntu/project/AIGC_web/.env.production",
  ],
  [
    "health alert repeat suppression",
    "scripts/check-health-alert.sh",
    "HEALTH_ALERT_REPEAT_SECONDS",
  ],
  [
    "central log retention",
    "deploy/observability/loki-config.yml",
    "retention_period: 720h",
  ],
  [
    "registration rollout",
    "app/api/auth/register/route.ts",
    "PUBLIC_REGISTRATION_ROLLOUT_PERCENT",
  ],
  [
    "runtime Loki verification",
    "scripts/verify-observability.mjs",
    "Nginx request log was not found in Loki",
  ],
  [
    "SMTP alert fallback",
    "scripts/send-alert-email.mjs",
    "ALERT_EMAIL_TO || user",
  ],
  [
    "daily rollout report guard",
    "scripts/gray-rollout-report.mjs",
    "ELIGIBLE_FOR_25_PERCENT",
  ],
  [
    "rollout report reads configured traffic",
    "scripts/gray-rollout-report.mjs",
    "PUBLIC_REGISTRATION_ROLLOUT_PERCENT || 10",
  ],
];

let failed = false;
for (const [name, path, expected] of checks) {
  const source = await readFile(path, "utf8");
  const ok = source.includes(expected);
  console.log(`${ok ? "PASS" : "FAIL"}: ${name}`);
  if (!ok) failed = true;
}
if (failed) process.exitCode = 1;
